name: size-limit

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          version: 11
      - uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
